version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=your-secret
    networks:
      - backend

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - JWT_SECRET=your-secret
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - JWT_SECRET=your-secret
    networks:
      - backend

networks:
  backend:
